<a href="https://colab.research.google.com/github/zeynep-serra/ML_Notes/blob/main/ModelSelection%26Boosting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# k fold cross validation
# split training set
# validation data shifts all folds
# metrics for all folds
# adjust hyperparameters / change model

# bias-variance tradeoff

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
data = pd.read_csv('ads.csv')
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.svm import SVC
classifier = SVC(kernel='rbf')
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[47  5]
 [ 1 27]]
0.925


In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier, X=X_train, y=y_train, cv=10)
print(accuracies)
print(accuracies.mean())
print(accuracies.std())

[0.96875 0.875   0.9375  0.96875 0.9375  0.84375 0.875   0.875   0.84375
 0.9375 ]
0.90625
0.046351240544347895


In [ ]:
# grid search cv
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
              {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'],
               'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator=classifier,
                           param_grid=parameters,
                           scoring='accuracy',
                           cv=10,
                           n_jobs=-1)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print(best_accuracy)
print(best_parameters)

0.909375
{'C': 0.5, 'gamma': 0.9, 'kernel': 'rbf'}


In [ ]:
classifier = SVC(kernel='rbf', gamma=0.9, C=0.5)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[48  4]
 [ 1 27]]
0.9375


In [ ]:
# xg boost
data = pd.read_csv('data_3.csv')
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

y = np.where(y == 2, 0, 1)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[78  1]
 [ 4 54]]
0.9635036496350365
